spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/abhishek
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
event_scheduler:
  retry:
    count: 4
  wait_duration: 500